apps/animals/urls.py
from django.urls import path
from .views import SpeciesListView,SpeciesAddView,SpeciesUpdateView,AnimalsListView,AnimalsAddView,AnimalUpdateView



urlpatterns = [
    path('species-list/',SpeciesListView.as_view(),name='species-list'),
    path('species-add/',SpeciesAddView.as_view(),name='species-add'),
    path('species-edit/<int:pk>',SpeciesUpdateView.as_view(),name='species-edit'),
    path('animals-list/',AnimalsListView.as_view(),name='animals-list'),
    path('animals-add/',AnimalsAddView.as_view(),name='animals-add'),
    path('animals-edit/<int:pk>',AnimalUpdateView.as_view(),name='animals-edit'),

]

scdv/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    # path("accounts/", include("apps.accounts.urls")),  # new
    path("accounts/", include("django.contrib.auth.urls")),
    path('animals/',include('apps.animals.urls')),
    path('vaccines/',include('apps.vaccines.urls')),
    path('',include('apps.core.urls')),
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

apps/animals/models.py
from distutils.command.upload import upload
from django.db import models
from apps.accounts.behaviors import Activible
from django.contrib.auth.models import User


# Create your models here.
class Specie(Activible):
    name = models.CharField(max_length=30,verbose_name='Nome')

    def __str__(self):
        return self.name

class Breed(Activible):
    name = models.CharField(verbose_name='Raça', max_length=30)
    specie = models.ForeignKey(Specie,on_delete=models.CASCADE,verbose_name='Espécie')
    def __str__(self):
        breed_name = self.name + ' - ' + self.specie.name
        return breed_name

class Animal(Activible):
    name = models.CharField(verbose_name='Nome',max_length=30)
    birthdate = models.DateField(verbose_name='Data de Nascimento')
    photo = models.ImageField(verbose_name='Foto',upload_to='photo/',null=True)
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    # specie = models.ForeignKey(Specie,on_delete=models.CASCADE,verbose_name='Espécie')
    breed = models.ForeignKey(Breed,on_delete=models.CASCADE,verbose_name='Raça',null=True)
    
    GENRES = (
        ('M', 'Masculino'), #Masculine
        ('F', 'Feminino'), #Feminine
    )

    gender = models.CharField(max_length=1,choices=GENRES,verbose_name='Gênero')
    
    def __str__(self):
        return self.name

apps/animals/forms.py
from django import forms
from .models import Specie,Animal

class DateInput(forms.DateInput):
    input_type = 'date'

    
class SpecieForm(forms.ModelForm):
    class Meta:
        model = Specie
        exclude = ('id',)

class AnimalsFilter(forms.Form):
    name = forms.TextInput()
    specie = forms.ModelChoiceField(
        label='Espécie',
        queryset=Specie.objects.filter(active=True),
        required = False
    )
    widgets = {
        'specie': forms.Select(attrs={'class': 'form-control'})
    }

class AnimalForm(forms.ModelForm):

    class Meta:
        model = Animal
        exclude = ('id','user')
        widgets = {
            'birthdate': DateInput(),
        }

apps/animals/views.py
from django.views.generic import ListView,CreateView,UpdateView,View
from django.shortcuts import render,redirect
from django.urls import reverse_lazy
from .forms import SpecieForm,AnimalsFilter,AnimalForm
from .models import Specie,Animal
from django.contrib.auth.models import User


class SpeciesListView(ListView):
    model = Specie
    template_name = 'species_list.html'

    def get_context_data(self,**kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['species'] = Specie.objects.filter(active=True)
        return ctx

class SpeciesAddView(CreateView):
    model = Specie
    form_class = SpecieForm
    success_message = 'Especie adicionada com sucesso!'
    template_name = 'species_form.html'
    success_url = reverse_lazy('species-list')

class SpeciesUpdateView(UpdateView):
    model = Specie
    form_class = SpecieForm
    success_message = 'Especie Editada com sucesso!'
    template_name = 'species_form.html'
    success_url = reverse_lazy('species-list')
    def get_context_data(self,**kwargs):
        ctx = super().get_context_data(**kwargs)
        return ctx
    
    def form_valid(self,form):
        specie_form = form.save()
        return redirect(self.success_url)

class AnimalsListView(View):
    template_name='animals_list.html'
    
    def get(self,request):
        ctx={}
        form = AnimalsFilter()
        ctx['form'] = form    
        ctx['animals'] = Animal.objects.filter(active=True,user=self.request.user)
        return render(request, self.template_name, ctx)

    def post(self,request):
        form = AnimalsFilter()
        ctx = {'form':form}

        animals = Animal.objects.filter(active=True,user=self.request.user)

        specie = request.POST.get('specie')
        if specie:
            animals = Animal.objects.filter(breed__specie=specie)
           
        ctx['animals'] = animals
        return render(request, self.template_name, ctx)

class AnimalsAddView(CreateView):
    model = Animal
    form_class = AnimalForm
    success_message = 'Animal adicionada com sucesso!'
    template_name = 'animals_form.html'
    success_url = reverse_lazy('animals-list')

    def form_valid(self,form):
        animal_form = form.save(commit=False)
        animal_form.user = User.objects.get(pk=self.request.user.id)
        animal_form.save()
        return redirect(self.success_url)


class AnimalUpdateView(UpdateView):
    model = Animal
    form_class = AnimalForm
    success_message = 'Animal Editado com sucesso!'
    template_name = 'animals_form.html'
    success_url = reverse_lazy('animals-list')
    def get_context_data(self,**kwargs):
        ctx = super().get_context_data(**kwargs)
        return ctx

    def form_valid(self,form):
        animal_form = form.save(commit=False)
        animal_form.active = True 
        animal_form.save()
        return redirect(self.success_url)

apps/animals/templates/animals_form.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}
{% load bootstrap5 %}


{% block content %}

<div class="container-fluid" id="principal">
    <form method="post" class="form" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="row">
            <div class="col-md-2">
                {% bootstrap_field form.name %}
            </div>
            <div class="col-md-1">
                {% bootstrap_field form.breed %}
            </div>
        </div>
        <div class="row">
            <div class="col-md-2">
                {% bootstrap_field form.birthdate %}
            </div>
            <div class="col-md-1">
                {% bootstrap_field form.gender %}
            </div>
        </div>
        <div class="row">
            {% if object.photo %}
            <div class="col-md-3    ">
                <div class="row">
                    <img src="{{object.photo.url}}" style="width: 250px; height: 250px;">
                    <div>
                        {% bootstrap_field form.photo %}
                    </div>
                </div>
            </div>
            {% else %}  
            <div class="col-md-3">
                <div>
                    {% bootstrap_field form.photo %}
                </div>
            </div>
            {% endif %}
        </div>
        <div class="row">
            <div class="col">
                <button class="btn btn-primary " type="submit"
                    onclick="this.disabled=true; this.form.submit();">Salvar</button>
                <a class="btn btn-danger " type="button" href="{% url 'animals-list' %}">Cancelar</a>
            </div>
        </div>
    </form>
</div>

{% block scripts%}
{% if object %}
<script>
    $('#id_user').val('{{user}}');
    $("#name-title").html("Editar Animal");
</script>
{% else %}
<script>
    $('#id_user').val('{{user}}');
    $("#name-title").html("Adicionar Animal");
</script>
{% endif %}
{% endblock%}
{% endblock%}

apps/animals/templates/animals_list.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% load i18n %}
{% load static %}

{% block content %}
<div class="container-fluid" id="principal">
    <form method="post" class="form">
        {% csrf_token %}
        <div class="row">
            <div class="col">
                {% bootstrap_field form.specie %}
            </div>
        </div>
        <div class="row">
            <div class="col-md-1" style="width: 75px;">
                <button type="submit" class="btn btn-info">{% trans 'Buscar' %}</button>
            </div>
            <div class="col-md-1">
                <a class="btn btn-primary " type="button" href="{% url 'animals-add' %}">Adicionar</a>
            </div>
        </div>
    </form>
    
    <br>
    {% if animals %}
    <div class="row ">
        <table class="table align-middle mb-0 bg-white">
            <thead>
                <tr>
                    <th>Nome</th>
                    <th>Raça</th>
                    <th>Dt. Nascimento</th>
                    <th>Ação</th>
                </tr>
            </thead>
            <tbody>
                {% for animal in animals %}
                <tr>
                    <!-- Icon -->
                    <td>
                        <div class="d-flex align-items-center">
                            <img src="{{animal.photo.url}}" alt=""
                                style="width: 45px; height: 45px" class="rounded-circle" />
                            <div class="ms-3">
                                <p class="fw-bold mb-1">{{animal.name}}</p>
                            </div>
                        </div>
                    </td>
    
                    <!-- Breed -->
                    <td>
                        <p class="fw-normal mb-1"> {{ animal.breed }}</p>
                    </td>
    
                    <!-- Birthdate -->
                    <td>
                        <p class="fw-normal mb-1"> {{ animal.birthdate }}</p>
                    </td>
    
                    <!-- Edit -->
                    <td>
                        <a type="button" class="btn btn-dark" href="{% url 'animals-edit' pk=animal.id %}"
                            style="margin-right: 3px;">Editar</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>    
    </div>
</div>
{% endif%}
{% block scripts%}
    <script>
        $("#name-title").html("Animais");
    </script>
{% endblock%}
{% endblock%}

apps/animals/templates/species_form.html
{% extends 'base.html' %}
{% load i18n %}
{% load bootstrap5 %}
{% load static %}

{% block content %}
<div class="container-fluid" id="principal">
    <form method="post" class="form">
        {% csrf_token %}
        <div class="row">
            <div class="col-md-2">
                {% bootstrap_field form.name %}
            </div>
        </div>

        <div class="row">
            <div class="col">
                <button class="btn btn-primary " type="submit"
                    onclick="this.disabled=true; this.form.submit();">Salvar</button>
                <a class="btn btn-danger " type="button" href="{% url 'species-list' %}">Cancelar</a>
            </div>
        </div>
    </form>
</div>
{% block scripts %}
    {% if object %}
    <script>
        $("#name-title").html("Editar Espécie");
    </script>
    {% else %}
    <script>
        $("#name-title").html("Adicionar Espécie");
    </script>
    {% endif%}
{% endblock %}
{% endblock%}

apps/animals/templates/species_list.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% load i18n %}
{% load static %}

{% block content %}
<div class="container-fluid" id="principal">    
    <div class="row">
        <div class="col-2">
            <a class="btn btn-primary " type="button" href="{% url 'species-add'%}" >Adicionar</a>
        </div>
    </div>
    {% if species %}
    <div class="row">
        <table class="table align-middle mb-0 bg-white"> 
            <thead>
                <tr>
                    <th> Id </th>
                    <th> Especie </th>
                    <th> Ativo </th>
                    <th> Ação </th>
                </tr>
            </thead>
            <tbody>
                {% for specie in species %}
                <tr>
                    <td>
                        <p class="fw-normal mb-1"> {{ specie.id }}</p>
                    </td>

                    <td>
                        <p class="fw-normal mb-1"> {{ specie.name }}</p>
                    </td>

                    <td>
                        <p class="fw-normal mb-1"> {{ specie.active }}</p>
                    </td>

                    <td>
                        <a type="button"  class="btn btn-dark" href="{% url 'species-edit' pk=specie.id %}" 
                        style="margin-right: 3px;">Editar</a>                        
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>   
    </div>
</div>
{% endif%}
{% block scripts %}
<script>
    $("#name-title").html("Espécies");
</script>
{% endblock %}
{% endblock%}