scdv/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    # path("accounts/", include("apps.accounts.urls")),  # new
    path("accounts/", include("django.contrib.auth.urls")),
    path('animals/',include('apps.animals.urls')),
    path('vaccines/',include('apps.vaccines.urls')),
    path('',include('apps.core.urls')),
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

apps/animals/models.py
from distutils.command.upload import upload
from django.db import models
from apps.accounts.behaviors import Activible
from django.contrib.auth.models import User


# Create your models here.
class Specie(Activible):
    name = models.CharField(max_length=30,verbose_name='Nome')

    def __str__(self):
        return self.name

class Breed(Activible):
    name = models.CharField(verbose_name='Raça', max_length=30)
    specie = models.ForeignKey(Specie,on_delete=models.CASCADE,verbose_name='Espécie')
    def __str__(self):
        breed_name = self.name + ' - ' + self.specie.name
        return breed_name

class Animal(Activible):
    name = models.CharField(verbose_name='Nome',max_length=30)
    birthdate = models.DateField(verbose_name='Data de Nascimento')
    photo = models.ImageField(verbose_name='Foto',upload_to='photo/',null=True)
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    # specie = models.ForeignKey(Specie,on_delete=models.CASCADE,verbose_name='Espécie')
    breed = models.ForeignKey(Breed,on_delete=models.CASCADE,verbose_name='Raça',null=True)
    
    GENRES = (
        ('M', 'Masculino'), #Masculine
        ('F', 'Feminino'), #Feminine
    )

    gender = models.CharField(max_length=1,choices=GENRES,verbose_name='Gênero')
    
    def __str__(self):
        return self.name

apps/animals/forms.py
from django import forms
from .models import Specie,Animal

class DateInput(forms.DateInput):
    input_type = 'date'

    
class SpecieForm(forms.ModelForm):
    class Meta:
        model = Specie
        exclude = ('id',)

class AnimalsFilter(forms.Form):
    name = forms.TextInput()
    specie = forms.ModelChoiceField(
        label='Espécie',
        queryset=Specie.objects.filter(active=True),
        required = False
    )
    widgets = {
        'specie': forms.Select(attrs={'class': 'form-control'})
    }

class AnimalForm(forms.ModelForm):

    class Meta:
        model = Animal
        exclude = ('id','user')
        widgets = {
            'birthdate': DateInput(),
        }

templates/base.html
{% load bootstrap5 %}
{% load static%}
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous">
  </script>
  <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
  <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>

  <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk="
    crossorigin="anonymous"></script>

  <link rel="stylesheet"
    href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0" />

  <script src={% static 'jquery-3.5.1.min.js' %}></script>
  <script src={% static 'jquery.formset.js' %}></script>
</head>
<style>
  .item-text {
    display: flex;
    align-items: center;
  }

  #principal {
    margin-top: 10px;
  }

  #id_breed,
  #id_gender,
  #id_specie {
    cursor: pointer;
  }

  .main {
    /* margin-left: 13rem;
    margin-right: 13rem;
    margin-top: 1rem; 
    align-items: center;*/

    width: 80%;
  }

  .item-menu{
    border-bottom: solid;
    border-width: 1px;
    border-color: rgb(198, 198, 198);
  }
  .form-select {
    width: 8rem;
    display: inline;
  }

  .form-label {
    font-size: 1rem;
    margin-right: 3px;
  }

  .title {
    text-align: center;
    font-size: 36px;
  }

  /* .item-header {
    background-color: rgb(239, 239, 239);
    padding-left: 13rem;
    padding-right: 13rem;
  } */

  /* .menu {
    border: 1px solid rgb(228, 222, 222);
  } */

  .sidebar {
    position: fixed;
    top: 0;
    bottom: 0;
    left: 0;
    z-index: 0;
    padding: 48px 0 0;
    /* Height of navbar */
    /* box-shadow: inset -1px 0 0 rgba(0, 0, 0, .1); */
    margin-top: 53px;
  }

  /* @media (max-width: 767.98px) {
  .sidebar {
    top: 5rem;
  }
} */
  .icon-menu{
    margin-right: 5px;
  }
  .sidebar-sticky {
    position: relative;
    top: 0;
    height: calc(100vh - 48px);
    padding-top: .5rem;
    overflow-x: hidden;
    overflow-y: auto;
    /* Scrollable contents if viewport is shorter than content. */
  }

  .sidebar .nav-link {
    font-weight: 500;
    color: #333;
  }

  .sidebar .nav-link .feather {
    margin-right: 4px;
    color: #727272;
  }

  .sidebar .nav-link.active {
    color: #2470dc;
  }

  .sidebar .nav-link:hover .feather,
  .sidebar .nav-link.active .feather {
    color: inherit;
  }

  .sidebar-heading {
    font-size: .75rem;
    text-transform: uppercase;
  }
</style>
{% if user.is_authenticated %}

<body>
  <header class="navbar navbar-light navbar-expand-lg navbar item-header flex-md-nowrap p-2"
    style="height: 53px; background-color: #f5f5f5;">
    <a href="/" class="navbar-brand col-md-3 col-lg-2 me-0 px-3">SCDV</a>
    <div class="navbar-collapse collapse w-100" id="collapsingNavbar3">
      <ul class="navbar-nav w-100 justify-content">
        <h3 id="name-title"> Base </h3>
      </ul>
      <ul class="nav navbar-nav ml-auto w-100 justify-content-end">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button"
            data-bs-toggle="dropdown" aria-expanded="false">
            {{user.username}}
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <li><a class="dropdown-item" href="{% url 'logout'%}">Sair</a></li>
          </ul>
        </li>
      </ul>
    </div>
  </header>

  <div class="container-fluid">
    <div class="row">
      <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block sidebar collapse" style="background-color: #f5f5f5;">
        <div class="position-sticky pt-3">
          <ul class="nav flex-column">
            <li class="nav-item item-menu ">
              <a class="nav-link" href="/">
                <div class="item-text">
                  <span class="material-symbols-outlined icon-menu">home</span>
                  Dashboard
                </div>
              </a>
            </li>
            <li class="nav-item item-menu">
              <a class="nav-link" aria-current="page" href="{% url 'animals-list'%}">
                <div class="item-text">
                  <span class="material-symbols-outlined icon-menu">pets</span>
                  Meus Animais
                </div>
              </a>
            </li>
            <li class="nav-item item-menu">
              <a class="nav-link" href="{% url 'vaccines-list'%}">
                <div class="item-text">
                  <span class="material-symbols-outlined icon-menu">vaccines</span>
                  Vacinas
                </div>
              </a>
            </li>
            <!-- <li class="nav-item item-menu">
              <a class="nav-link" href="{% url 'species-list'%}">
                <div class="item-text">
                  <span class="material-symbols-outlined icon-menu">groups_2</span>
                  Especies
                </div>
              </a>
            </li> -->
          </ul>
        </div>
      </nav>

      <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
        <div
          class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
          {% block content %}
          {% endblock %}
        </div>

      </main>
      <!-- <main class="main"> -->

      <!-- </main> -->

      <script src="https://cdn.jsdelivr.net/npm/feather-icons@4.28.0/dist/feather.min.js"
        integrity="sha384-uO3SXW5IuS1ZpFPKugNNWqTZRRglnUJK6UAZ/gxOX80nxEkN9NcGZTftn6RzhGWE" crossorigin="anonymous">
      </script>
      <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.js"
        integrity="sha384-zNy6FEbO50N+Cg5wap8IKA4M/ZnLJgzc6w2NqACZaK0u0FXfOWRRJOnQtpZun8ha" crossorigin="anonymous">
      </script>
</body>


{% else %}
<p>You are not logged in</p>
<a href="{% url 'login' %}">Log In</a>
{%endif%}

</html>

templates/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
{% if user.is_authenticated %}
{% include "modals/modal_application.html" with application_form=application_form vaccine_form=vaccine_form %}
<div class="container-fluid">


    <!-- Filters -->
    <div class="row">
        <div class="col-1">
            <h5>Filtros:</h5>
        </div>
        <div class="col-2">
            <input type="text" placeholder="Busca" class="form-control">
        </div>
        <div class="col-2">
            <input type="date" class="form-control" placeholder="data inicio">
        </div>
        <div class="col-2">
            <input type="date" class="form-control" placeholder="data fim">
        </div>
        <div class="col-2">
            <input type="select" class="form-control" placeholder="Raça">
        </div>
        <div class="col-1">
            <button type="submit" class="btn btn-dark">Pesquisar</button>
        </div>
    </div>
    <hr>
    <!-- Div Nova Vacina -->

    <div class="row" style="margin-top: 10px;">
        <div class="col-6" style="width: 66%; height: 730px; background: #f2f2f2; border-radius: 5px; border: 1px solid;">
            <div class="row" style="margin-top: 1%;">
                <div class="col-10">
                    <h4 style="justify-content: center; margin-top: 1%;" >Histórico (Ultimas 10)</h4>
                </div>
                <div class="col-2">
                    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#modal_application">
                        Vacinar
                    </button>
                </div>
            </div>
            
            <table class="table align-middle mb-0">
                <thead> 
                    <tr>
                        <th>Nome</th>
                        <th>Raça</th>
                        <th>Dt. Aplicação</th>
                        <!-- <th>Ação</th> -->
                    </tr>
                </thead>
                <tbody>
                    {% for application in applications %}
                    <tr>
                        <!-- Icon -->
                        <td>
                            <div class="d-flex align-items-center">
                                <img src="{{ application.animal.photo.url }}" alt=""
                                    style="width: 45px; height: 45px" class="rounded-circle" />
                                <div class="ms-3">
                                    <p class="fw-bold mb-1">{{application.animal.name}}</p>
                                </div>
                            </div>
                        </td>
        
                        <!-- Breed -->
                        <td>
                            <p class="fw-normal mb-1"> {{application.animal.breed}}</p>
                        </td>
        
                        <!-- Birthdate -->
                        <td>
                            <p class="fw-normal mb-1"> {{application.add_date}}</p>
                        </td>
        
                        <!-- Edit
                        <td>
                            <a type="button" class="btn btn-dark" href=""
                                style="margin-right: 3px;">Editar</a>
                        </td> -->
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="col-6" style="width: 30%; height: 400px; background: #DBDBDB; margin-left: 10px; border-radius: 5px; border: 1px solid;">
            <h4 style="margin-top: 3%;">Alertas (Próximos 15 dias)</h4>
            <hr>
            <table class="table align-middle mb-0">
                <tbody>
                    {% for next in next_applications %}
                    <tr>
                        <td>
                            <div class="d-flex align-items-center">
                                <img src="{{ next.application.animal.photo.url }}" alt=""
                                    style="width: 45px; height: 45px" class="rounded-circle" />
                            </div>
                        </td>
                        <td> {{next.application.animal}} </td>
                        <td> {{next.vaccine}} </td>
                        <td> {{next.notify_date}} </td>
                    </tr>
                    {% endfor %}
                </tbody>
        </div>
    </div>
</div>
{% else %}
<p>You are not logged in</p>
<a href="{% url 'login' %}">Log In</a>
{% endif %}

{% block scripts %}
<script>
    $("#name-title").html("Dashboard");
</script>
{% endblock %}

{% endblock %}